name: Test Visual Studio Code

on: [push, pull_request]


- uses: game-ci/unity-test-runner@v2
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    projectPath: .
    githubToken: ${{ secrets.GITHUB_TOKEN }}